### ISSUE TITLE
高解像度にも対応した仕様にして欲しいです。

### ISSUE THREAD

**Issue by Sachimitama** [anoyetta-academy/kagami#3]
アイコンやフォントの大きさを変えられるようにして欲しいです。今のままだとあまりにもアイコンや文字が小さすぎてわかりづらいです。これはFF側で解像度を上げるなりしないと改善出来ないのでしょうか？高解像度のプレイ環境にも対応して欲しいです。また、動作はしますが以下のエラーが出ます。

2019/12/01 12:21:52: Error: Kagami: ThreadWorker - Sharlayan Process Subscriber error. System.NotSupportedException: WebClient は同時 I/O 操作をサポートしません。
   場所 System.Net.WebClient.ClearWebClientState()
   場所 System.Net.WebClient.DownloadString(Uri address)
   場所 Sharlayan.Utilities.APIHelper.GetSignatures(ProcessModel processModel, String patchVersion)
   場所 Sharlayan.MemoryHandler.SetProcess(ProcessModel processModel, String gameLanguage, String patchVersion, Boolean useLocalCache, Boolean scanAllMemoryRegions)
   場所 kagami.Helpers.SharlayanHelper.DetectFFXIVProcess()
   場所 kagami.Helpers.Common.ThreadWorker.DoWorkLoop()

よろしくお願いします。

**Comment by anoyetta** [comment]
それはフロントエンド側の話なので私の方で出来ることはないです。
また高解像度にも対応していると思います。使い方や設定の問題ではないかと思います。
