### ISSUE TITLE
アイコンの大きさやフォントのサイズを変更出来るようにして欲しい

### ISSUE THREAD

**Issue by Sachimitama** [anoyetta-academy/kagami#4]
現在、高い解像度での仕様のせいかオーバーレイのサイズや表記されている文字やアイコンが
あまりにも小さすぎて見えづらく不便なので変更可能にして欲しいです。またACTの実行ファイルのプロパティから高DPI設定でフォントを上書きしないようにしないとACT自体のフォントが崩れて表記が見えなくなったりするも改良出来ないでしょうか？よろしくお願いします。

**Comment by anoyetta** [comment]
それはフロントエンド側なのでDLL側では制御できません。
自分でCSSを書き換えたらよいかと。
ACT本体についてもこちらで制御するものではないです。
